name: Publish to PyPI

on:
  release:
    types: [published] # Triggers when you publish a GitHub Release

jobs:
  pypi-publish:
    name: Build and Release to PyPI
    runs-on: ubuntu-latest
    
    # Required for Trusted Publishing authentication
    permissions:
      id-token: write
      contents: read

    # Matches the environment name set on PyPI
    environment:
      name: release

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Build Package
        run: uv build

      - name: Publish to PyPI
        run: uv publish
